sudo: false
language: node_js
node_js:
  - "10"

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - GITHUB_REPO: "alajfit/vue-run"

install:
  - npm ci

script:
  - npm run lint

branches:
  only:
    - master